version: "3.3"
services:
    atlantis:
        image: runatlantis/atlantis:latest
        environment:
            - HOSTNAME=$HOSTNAME
            - ATLANTIS_ATLANTIS_URL=$ATLANTIS_ATLANTIS_URL
            - ATLANTIS_GITLAB_USER=$ATLANTIS_GITLAB_USER
            - ATLANTIS_GITLAB_TOKEN=$ATLANTIS_GITLAB_TOKEN
            - ATLANTIS_GITLAB_WEBHOOK_SECRET=$ATLANTIS_GITLAB_WEBHOOK_SECRET
            - ATLANTIS_GITLAB_HOSTNAME=$ATLANTIS_GITLAB_HOSTNAME
            - ATLANTIS_REPO_WHITELIST=$ATLANTIS_REPO_WHITELIST
            - ATLANTIS_TFE_TOKEN=$ATLANTIS_TFE_TOKEN
            - ATLANTIS_REPO_CONFIG_JSON=$ATLANTIS_REPO_CONFIG_JSON
        deploy:
          replicas: 1
          labels:
            - com.df.notify=true
            - com.df.port=4141
            - com.df.httpsOnly=false
            - com.df.serviceDomain=atlantis-tf.cablelabs.com
            - com.df.servicePath=/
        networks:
          - proxy
networks:
  proxy:
    external: true
