version: '3'

services:
    minio1:
        image: minio/minio
        hostname: minio1
        volumes:
            - docker-data1:/export
        ports:
            - "9001:9000"
        networks:
            - minio_distributed
        environment:
            MINIO_ACCESS_KEY: JVHPHHVZ5ALC4398ZHJQCD
            MINIO_SECRET_KEY: bUQnd7UFy6dG50JoJovNabzj*Szzm35LB^04fwZ
        deploy:
            restart_policy:
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - node.labels.minio1==true
        command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

    minio2:
        image: minio/minio
        hostname: minio2
        volumes:
            - docker-data2:/export
        ports:
            - "9002:9000"
        networks:
            - minio_distributed
        environment:
            MINIO_ACCESS_KEY: JVHPHHVZ5ALC4398ZHJQCD
            MINIO_SECRET_KEY: bUQnd7UFy6dG50JoJovNabzj*Szzm35LB^04fwZ
        deploy:
            restart_policy:
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - node.labels.minio2==true
        command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

    minio3:
        image: minio/minio
        hostname: minio3
        volumes:
            - docker-data3:/export
        ports:
            - "9003:9000"
        networks:
            - minio_distributed
        environment:
            MINIO_ACCESS_KEY: JVHPHHVZ5ALC4398ZHJQCD
            MINIO_SECRET_KEY: bUQnd7UFy6dG50JoJovNabzj*Szzm35LB^04fwZ
        deploy:
            restart_policy:
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - node.labels.minio3==true
        command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

    minio4:
        image: minio/minio
        hostname: minio4
        volumes:
            - docker-data4:/export
        ports:
            - "9004:9000"
        networks:
            - minio_distributed
        environment:
            MINIO_ACCESS_KEY: JVHPHHVZ5ALC4398ZHJQCD
            MINIO_SECRET_KEY: bUQnd7UFy6dG50JoJovNabzj*Szzm35LB^04fwZ
        deploy:
            restart_policy:
                delay: 10s
                max_attempts: 10
                window: 60s
            placement:
                constraints:
                    - node.labels.minio4==true
        command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 

volumes:
    docker-data1:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/data'
    docker-data2:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/data'
    docker-data3:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/data'
    docker-data4:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/data'

networks:
    minio_distributed:
        driver: overlay
