version: "3.3"
services:
    sonarqube:
        image: sonarqube:lts
        deploy:
            replicas: 1
            labels:
                - com.df.notify=true
                - com.df.port=9000
                - com.df.httpsOnly=false
                - com.df.serviceDomain=sonar.cablelabs.com
                - com.df.servicePath=/
        environment:
            - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
        volumes:
            - /data/sonar/conf:/opt/sonarqube/conf
            - /data/sonar/data:/opt/sonarqube/data
            - /data/sonar/logs:/opt/sonarqube/logs
            - /data/sonar/extensions:/opt/sonarqube/extensions 
        networks:
            - sonarnet
            - proxy

    db:
        image: postgres
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - /data/sonar/data:/var/lib/postgresql/data
        networks:
            - sonarnet

networks:
    sonarnet:
        external: true
    proxy:
        external: true
